import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { toast } from "react-toastify";
import Link from "next/link";

import React, { useState } from "react";
import { addDoc, collection } from "firebase/firestore";
import {
  getAuth,
  createUserWithEmailAndPassword,
  fetchSignInMethodsForEmail,
} from "firebase/auth";
import db from "@/app/lib/firestore";
import { sign } from "crypto";
import { auth } from "@/app/lib/fireabse";
import Dropdown from "./utilities/dropDownProfile";
import Navbar from "./utilities/navBar";
import { AuthProvider } from "@/app/context/authContext";

//TODO: find a way to make profile dropdown a logout option when there is a user to logout for

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex min-h-screen flex-col">
            <div className="relative z-[10]">
              <div
                className="relative z-[10] h-full w-full bg-[#f0f0f8]"
                style={{
                  backgroundImage: "url('/assets/SC_background.webp')",
                  backgroundSize: "cover",
                  backgroundRepeat: "repeat",
                  backgroundPosition: "center",
                }}
              >
                <div className="z-50">
                  <Navbar />
                </div>

                <div className="relative h-auto w-auto flex-1">{children}</div>

                {/* <div
                  className="relative z-[10] flex border-8 border-black bg-gray-400"
                  id="footer"
                >
                  <div className="mx-auto w-full">
                    <div className="flex outline outline-red-500" id="first">
                      <div className="flex-1 text-center text-black outline outline-red-500">
                        ABOUT US
                      </div>
                      <div className="flex-1 text-center text-black outline outline-red-500">
                        How can we help?
                      </div>
                      <div className="flex-1 text-center text-black outline outline-red-500">
                        Sell
                      </div>
                    </div>
                    <div className="flex outline outline-red-500">
                      <div className="flex-1 text-left text-black">Connect</div>
                    </div>
                    <div className="flex justify-center outline outline-red-500">
                      <div className="text-black">Legal Disclaimer</div>
                    </div>
                  </div>
                </div> */}
              </div>
            </div>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
